# Generated by Django 5.2 on 2025-04-21 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cycle', models.CharField(choices=[('yr', 'Yearly'), ('mn', 'Monthly')], max_length=3)),
                ('start_date', models.DateField(default=datetime.date(2025, 4, 21))),
                ('category', models.CharField(choices=[('ent', 'Entertainment'), ('wrk', 'Work'), ('grc', 'Groceries')], max_length=3)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
