# Generated by Django 5.2 on 2025-04-22 22:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='start_date',
            field=models.DateField(default=datetime.date(2025, 4, 22)),
        ),
    ]
