# Generated by Django 5.2 on 2025-04-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_subscriptions_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
