# Generated by Django 5.2 on 2025-04-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_subscriptions_total_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
    ]
