# Generated by Django 5.2 on 2025-04-23 00:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_subscriptions_total_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='next_payment',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='start_date',
            field=models.DateField(default=datetime.date(2025, 4, 23)),
        ),
    ]
