# Generated by Django 5.2 on 2025-04-28 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_subscriptions_next_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptions',
            name='total_spent',
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='start_date',
            field=models.DateField(default=datetime.date(2025, 4, 28)),
        ),
    ]
