# Generated by Django 5.2 on 2025-04-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_subscriptions_total_spent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='total_spends',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
    ]
