# Generated by Django 5.2 on 2025-04-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_subscriptions_total_spends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='category',
            field=models.CharField(choices=[('Entertainment', 'Entertainment'), ('Work', 'Work'), ('Groceries', 'Groceries')], max_length=20),
        ),
    ]
