# Generated by Django 5.2 on 2025-04-29 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_subscriptions_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='start_date',
            field=models.DateField(default=datetime.date(2025, 4, 29)),
        ),
    ]
